### ISSUE TITLE
Delete local data before saving new ones

### ISSUE THREAD

**Issue by Twist96** [Twist96/SwiftRepos#1]
I'm trying to delete all data in the database before saving a new set of data. For this to happen properly, I have to wait for the delete process to be over.

```saveAllRepositories()``` function in ```HomeViewModel.swift``` handles the logic for deleting data before writing

```deleteAll()``` function  in```DataController.swift```  does batch delete, while ```deletePersistantStore()``` in the same file is an alternative method to delete database content. ```deletePersistantStore()``` deletes the entire database and tries to recreat it again.

```deleteAll()``` fails to finish deleting data before write operation starts, while ```deletePersistantStore()``` fails to proceed with write operation after dropping the database.

**Comment by LucasVanDongen** [comment]
I think you shouldn't delete the contents of you local storage because what is the whole point of having a cache if you delete it immediately? I think you should insert / update / delete the new contents in such a way you update the existing rows instead. Publisher + Reponame can be the unique ID.

**Comment by Twist96** [comment]
Thank you, upsert fixed it.
